//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventDetails
    {
        [Key]
        public long EventDetailsId { get; set; }
        public long EventId { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> EventSubTypeId { get; set; }
        public int SurfaceTypeId { get; set; }
        public Nullable<int> ScheduleTypeId { get; set; }
        public string Location { get; set; }
        public string EmployeeRange { get; set; }
        public int CreatedBy { get; set; }
        public DateTime ExpectedToConduct { get; set; }

        public Nullable<bool> IsDeleted { get; set; }
        public virtual Event Event { get; set; }
        public virtual EventSubType EventSubType { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual SurfaceType SurfaceType { get; set; }
    }
}
