//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventDetails = new HashSet<EventDetails>();
        }
    
        public long EventId { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string EmployeeRange { get; set; }
        public Nullable<System.DateTime> ExpectedToConduct { get; set; }
       // public Nullable<long> VendorId { get; set; }
        public Nullable<int> ScheduleTypeId { get; set; }
        public string Location { get; set; }
    
        public virtual ScheduleType ScheduleType { get; set; }
        public virtual EventStatusType EventStatusType { get; set; }
        public virtual ICollection<EventDetails> EventDetails { get; set; }
    }
}
