//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType_Place
    {
        public int Id { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> EventSubTypeId { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual EventSubType EventSubType { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Place Place { get; set; }
    }
}
