//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.EF
{
    using System;
    using System.Collections.Generic;

    public partial class Organiser
    {
        public long OrganiserId { get; set; }
        public string OrganiserName { get; set; }
        public string OrganiserDescription { get; set; }
        public Nullable<long> UserId { get; set; }
        public string OrganiserLogo { get; set; }
        public string RecordStatus { get; set; }
        public User user { get; set; }
    }
}
