//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurfaceType
    {
        public SurfaceType()
        {
            this.EventDetails = new HashSet<EventDetails>();
        }
    
        public int SurfaceTypeId { get; set; }
        public string SurfaceType1 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<EventDetails> EventDetails { get; set; }
    }
}
