//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long AddressId { get; set; }
        public string Address1 { get; set; }
        public long Pin { get; set; }
        public long PersonTypeId { get; set; }
        public long LookUpAddressTypeId { get; set; }
        public string RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual LookUpAddressType LookUpAddressType { get; set; }
        public virtual User User { get; set; }
    }
}
