//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            //this.EventDetails = new HashSet<EventDetail>();
            //this.EventSubTypes = new HashSet<EventSubType>();
            //this.EventType_Place = new HashSet<EventType_Place>();
        }
    
        public int EventTypeId { get; set; }
        public string EventTypeName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
       // public virtual ICollection<EventDetail> EventDetails { get; set; }
        public virtual ICollection<EventSubType> EventSubTypes { get; set; }
       // public virtual ICollection<EventType_Place> EventType_Place { get; set; }
    }
}
