//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUpUserType
    {
        public LookUpUserType()
        {
            this.Users = new HashSet<User>();
        }
    
        public long LookUpUserTypeId { get; set; }
        public string UserType { get; set; }
        public string RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
