//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impulse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Status { get; set; }
        public long UserId { get; set; }      
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LookUpUserTypeName { get; set; }
        public long LookUpUserTypeId { get; set; }
        public Nullable<long> LookUpUserStatusId { get; set; }
        public string LookUpUserStatusName { get; set; }
        public string RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserType { get; set; }
    
        public virtual LookUpUserType LookUpUserType { get; set; }
        
        public LookUpUserStatus LookUpUserStatus { get; set; }
        public Company Company { get; set; }
        public List<Contact> Contact { get; set; }
        public List<VendorInterest> VendorInterest { get; set; }
        public Team Team { get; set; }
        public VendorInvitation VendorInvitation { get; set; }
        public Citizen Citizen { get; set; }
    }
}
